name: latentneural
dependencies:
  - python=3.8
  - jupyter
  - matplotlib
  - numpy
  - scikit-learn>=0.24.*
  - scipy
  - tensorflow>=2.*
  - tensorflow-gpu
  - pip=21.0.1
  - pytest
  - pip:
    - google-auth-oauthlib==0.4.4
    - google-auth==1.30.1
    - google-pasta==0.2.0
    - jax==0.1.75
    - jaxlib==0.1.51
    - -e .
variables:
  KMP_DUPLICATE_LIB_OK: True
  XLA_FLAGS: "--xla_gpu_cuda_data_dir=/home/alessandrofacchin/xla"
  