name: latentneural-cpu
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python=3.8
  - h5py
  - imageio
  - ipykernel
  - ipympl
  - jupyter
  - matplotlib
  - mypy
  - numpy<1.20
  - scikit-learn>=0.24.*
  - scipy
  - tensorflow>=2.*
  - tensorflow-probability
  - pandas
  - pip=20.2.*
  - plotly
  - pytest
  - pip:
    - --requirement requirements.cpu.txt
variables:
  KMP_DUPLICATE_LIB_OK: True
  XLA_FLAGS: "--xla_gpu_cuda_data_dir=/home/alessandrofacchin/xla"
  CPU_ONLY: "TRUE"
  